name: Publish package to NuGet

on:
  release:
    types: [published, edited]
    tags: 
    - DotNet*
    
jobs:
  pack-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.12
        
    - name: Generate package
      run: dotnet pack ./CSharpDiscordWebhook.NET/CSharpDiscordWebhook.NET.csproj -c Release -o CSharpDiscordWebhook.NET_Package
      
    - name: Upload
      run: |
        cd CSharpDiscordWebhook.NET_Package
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
